# дополнительные параметры модулей приёма данных с устойств слежения
# служит для корректного отображения на клиентских приложениях информации о настройках подключения УС
DeviceModelsConfig:
    # Указывает внешний IP-адрес или DNS-имя отображаемое на клиенте для настройки УС.
    # Если не указано используется PublicAddress сервиса.
    ExternalAddress: xxx.xxx.xxx.xxx

    # Указывает какой внешний порт соответствует внутреннему
    # Формат: <internal_port>: <external_port>
    # Если соспоставление не найдено - будет использоваться внутренний порт без изменения
    PortsMapping:
        8223: 8223
        8224: 8224
        8225: 8225
